apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-volume.yaml
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - embed-deployment.yaml
  - embed-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - widget-deployment.yaml
  - widget-service.yaml
  - ws-deployment.yaml
  - ws-service.yaml
  - worker-deployment.yaml
  - worker-service.yaml
 

# namespace
# Adds namespace to all resources.
namespace: teleflow

nameSuffix: -dev

namePrefix: teleflow-

commonLabels:
  owner: teleflow

configMapGenerator:
  - envs:
      - env-dev
    name: teleflow-env
