apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.teleflow.khulnasoft.com/name: ws
  name: ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app.teleflow.khulnasoft.com/name: ws
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        app.teleflow.khulnasoft.com/name: ws
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: teleflow-env
          image: ghcr.io/khulnasoft/teleflow/ws:0.23.0
          name: ws
          ports:
            - containerPort: 3002
