apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    app.teleflow.khulnasoft.com/name: ws
  name: ws
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3002
  selector:
    app.teleflow.khulnasoft.com/name: ws
